Feature/tuan nt 002 api forgot password
vfa-khuongdv/tranining-internship-2023-07 pull request #2
Opened 2023-07-12 08:56 UTC by tuannt02

@vfa-khuongdv Hi anh Khương, nhờ anh review giúp em với ạ

2023-07-12 11:00 UTC, vfa-khuongdv requested changes

2023-07-12 11:00 UTC, vfa-khuongdv commented on src/modules/users/users.controller.ts
> +  forgotPassword(@Param() forgotPwParamDto: ForgotPasswordDto) {
@tuannt02 
Chỗ này em truyền vậy lộ email, em đổi thành method post nha.

2023-07-13 03:13 UTC, tuannt02 commented on src/modules/users/users.controller.ts
> +  forgotPassword(@Param() forgotPwParamDto: ForgotPasswordDto) {
Dạ, em commit lên lại nha anh,

2023-07-18 01:19 UTC, vfa-khuongdv commented
@tuannt02 
Resolved conflict nha Tuấn.

2023-07-18 01:19 UTC, merged