Feature/tuan nt 003 api reset password
vfa-khuongdv/tranining-internship-2023-07 pull request #3
Opened 2023-07-12 10:07 UTC by tuannt02

@vfa-khuongdv Hi anh Khương, nhờ anh review giúp em với ạ

2023-07-12 11:02 UTC, vfa-khuongdv requested changes

2023-07-12 11:02 UTC, vfa-khuongdv commented on src/modules/users/users.controller.ts
> +  @Post('/api/users/:email/reset-password/:token')
@tuannt02 
Em check lại desc của task trên trello nha, chưa match với yêu cầu.

2023-07-13 03:37 UTC, tuannt02 commented on src/modules/users/users.controller.ts
> +  @Post('/api/users/:email/reset-password/:token')
@vfa-khuongdv  Em vừa fix phù hợp với yêu cầu í anh. Anh check lại giúp em nha.

2023-07-13 03:47 UTC, tuannt02 commented on src/modules/users/users.controller.ts
> +  @Post('/api/users/:email/reset-password/:token')
Em vừa fix anh review lại giúp em với nha.

2023-07-13 12:56 UTC, merged